import { App, Stack } from 'aws-cdk-lib';
import {
  OrgAccountInit,
  OrgEvent,
  OrgSlack,
} from './index';

const disableArnsBasicAll = [
  'ACM.1',
  'APIGateway.1',
  'APIGateway.2',
  'APIGateway.3',
  'APIGateway.4',
  'APIGateway.5',
  'AutoScaling.1',
  'CloudTrail.1',
  'CloudTrail.2',
  'CloudTrail.4',
  'CloudTrail.5',
  'CodeBuild.1',
  'CodeBuild.2',
  'Config.1',
  'DMS.1',
  'DynamoDB.1',
  'DynamoDB.2',
  'DynamoDB.3',
  'EC2.10',
  'EC2.15',
  'EC2.16',
  'EC2.17',
  'EC2.18',
  'EC2.19',
  'EC2.2',
  'EC2.4',
  'EC2.6',
  'EC2.7',
  'EC2.8',
  'EC2.9',
  'ECS.1',
  'ECS.2',
  'EFS.1',
  'EFS.2',
  'ELB.3',
  'ELB.4',
  'ELB.5',
  'ELB.6',
  'ELB.7',
  'ELBv2.1',
  'EMR.1',
  'ES.1',
  'ES.2',
  'ES.3',
  'ES.4',
  'ES.5',
  'ES.6',
  'ES.7',
  'ES.8',
  'ElasticBeanstalk.1',
  'ElasticBeanstalk.2',
  'GuardDuty.1',
  'IAM.1',
  'IAM.2',
  'IAM.21',
  'IAM.3',
  'IAM.4',
  'IAM.5',
  'IAM.6',
  'IAM.7',
  'IAM.8',
  'KMS.1',
  'KMS.2',
  'Lambda.1',
  'Lambda.2',
  'RDS.10',
  'RDS.12',
  'RDS.13',
  'RDS.14',
  'RDS.15',
  'RDS.16',
  'RDS.17',
  'RDS.18',
  'RDS.19',
  'RDS.2',
  'RDS.20',
  'RDS.21',
  'RDS.22',
  'RDS.23',
  'RDS.3',
  'RDS.4',
  'RDS.5',
  'RDS.6',
  'RDS.7',
  'RDS.8',
  'RDS.9',
  'Redshift.1',
  'Redshift.2',
  'Redshift.3',
  'Redshift.4',
  'Redshift.6',
  'Redshift.7',
  'S3.1',
  'S3.2',
  'S3.3',
  'S3.6',
  'S3.8',
  'SNS.1',
  'SQS.1',
  'SSM.1',
  'SSM.2',
  'SSM.3',
  'SageMaker.1',
  'SecretsManager.1',
  'SecretsManager.2',
  'SecretsManager.3',
  'SecretsManager.4',
];
const disableArnsBasicVA = [
  'CloudFront.1',
  'CloudFront.2',
  'CloudFront.3',
  'CloudFront.4',
  'CloudFront.5',
  'CloudFront.6',
  'WAF.1',
];

const disableArnsCISAll = [
  '1.1',
  '1.10',
  '1.11',
  '1.14',
  '1.20',
  '1.3',
  '1.4',
  '1.5',
  '1.6',
  '1.7',
  '1.8',
  '1.9',
  '2.1',
  '2.2',
  '2.3',
  '2.4',
  '2.5',
  '2.6',
  '2.7',
  '2.8',
  '3.1',
  '3.10',
  '3.11',
  '3.12',
  '3.13',
  '3.14',
  '3.2',
  '3.3',
  '3.4',
  '3.5',
  '3.6',
  '3.7',
  '3.8',
  '3.9',
  '4.3',
];
const disableArnsCISNotCtHome = [
  '1.12',
  '1.13',
  '1.16',
  '1.2',
  '1.2',
];

const controlTowerHomeRegion = 'ap-northeast-1';
const auditAccountId = '123412341234';
const auditRegion = 'ap-northeast-1';
const roleName = 'swrole-from-blea';

const app = new App();

const AuditStack = new Stack(app, 'AuditStack',
  {
    env: {
      account: auditAccountId,
      region: auditRegion,
    },
  },
);

const orgEvent = new OrgEvent(AuditStack, 'OrgEvent', {
  region: 'ap-northeast-1',
  accountId: '123456789012',
  kmsAliasName: 'jicOrgTest',
});

new OrgSlack(AuditStack, 'OrgSlack', {
  snsTopic: [orgEvent.topic],
  workspaceId: 'xxxxxxx',
  channelId: 'xxxxxxx',
  slackChannelConfigurationName: 'xxxxxxx',
});

new OrgAccountInit(AuditStack, 'OrgAccountInit', {
  roleName: roleName,
  disableArnsBasicAll: disableArnsBasicAll,
  disableArnsCISAll: disableArnsCISAll,
  disableArnsBasicVA: disableArnsBasicVA,
  disableArnsCISNotCtHome: disableArnsCISNotCtHome,
  controlTowerHomeRegion: controlTowerHomeRegion,
});