// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for DisableShubFunction
 */
export interface DisableShubFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda/disableShub.
 */
export class DisableShubFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DisableShubFunctionProps) {
    super(scope, id, {
      description: 'src/lambda/disableShub.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/lambda/disableShub.lambda')),
    });
  }
}