// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SwroleFunction
 */
export interface SwroleFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda/swrole.
 */
export class SwroleFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: SwroleFunctionProps) {
    super(scope, id, {
      description: 'src/lambda/swrole.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/lambda/swrole.lambda')),
    });
  }
}